# Generated by Django 2.2.1 on 2019-06-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hepprofilemodel',
            old_name='login_id',
            new_name='uuid',
        ),
    ]
