# Generated by Django 2.2.1 on 2019-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HepProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=128)),
                ('cellphone', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('newid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.IntegerField(default=12)),
            ],
        ),
    ]
