# Generated by Django 2.2.1 on 2019-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_paymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=128)),
                ('txid', models.CharField(db_index=True, max_length=128)),
            ],
        ),
    ]
